# Fonts
font_family      JetBrainsMono Nerd Font
font_size        12
bold_font        auto
italic_font      auto
bold_italic_font auto

# Cursor
cursor_shape     block
shell_integration no-cursor

# Mouse
mouse_hide_wait  2.0

# URLs
url_style        dotted
url_color        #0087bd
detect_urls      yes
open_url_with    default

# Windows 
enabled_layouts  fat,tall,stack
confirm_os_window_close 0
background_opacity 0.95
placement_strategy center

#Tabs
tab_bar_edge     top
tab_bar_style    powerline 
tab_powerline_style angled
tab_bar_align    left 

# Keyboard Shortcuts
kitty_mod ctrl+shift
map ctrl+alt+enter launch --cwd=current
action_alias launch_tab launch --type=tab --cwd=current
map ctrl+t launch_tab
map f1 launch_tab nvim
map f2 launch_tab yazi
map f3 launch_tab lazygit

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
