"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = [
    "g",
    "d",
  ], run = "cd ~/.local/share/Trash/files", desc = "Goto Wastebasket" },
  { on = [
    "g",
    "l",
  ], run = "cd ~/.local", desc = "Goto ~/.local" },
  { on = "M", run = "plugin mount" },
  { on = "S", run = "search --via=rga", desc = "Search files by content via ripgrep" },
]
