$mainMod = SUPER

bind = $mainMod, SPACE, exec, $HOME/.config/wofi/scripts/desktop.sh
bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, W, exec, firefox
bind = ALT, code:21, exec, galculator
bind = $mainMod, E, exec, thunar


bind = $mainMod, M, exec, wlogout --protocol layer-shell
bind = $mainMod, I, exec, $HOME/.config/hypr/hypridle.sh
bind = $mainMod SHIFT, M, exit,
bind = ,code:107, exec, grim -g "$(slurp)" - | swappy -f -
bind = $mainMod, O, exec, $HOME/.config/wofi/scripts/wallpaper-switcher.sh
bind = $mainMod, TAB, exec, hyprshade toggle blue-light-filter
bind = ALT, TAB, exec, $HOME/.config/wofi/scripts/task-switcher.sh


# Window Controls
bind = $mainMod, V, togglefloating,
bind = $mainMod SHIFT, V, exec, hyprctl keyword windowrule float,title:
bind = $mainMod CTRL, V, exec, hyprctl keyword windowrule tile,title:
bind = $mainMod, Q, killactive,
bind = $mainMod, P, pseudo,
bind = $mainMod, S, togglesplit,
bind = $mainMod, F, fullscreen, 1
bind = $mainMod, D, exec, hyprctl --batch "keyword decoration:rounding 3 ; keyword general:gaps_out 2 ; keyword general:gaps_in 2 ; keyword general:border_size 2"
bind = $mainMod CTRL, D, exec, hyprctl --batch "keyword decoration:rounding 0 ; keyword general:gaps_out 0 ; keyword general:gaps_in 0 ; keyword general:border_size 0"
bind = $mainMod SHIFT, F, fullscreen
bind = $mainMod SHIFT, BACKSPACE, exec, pkill waybar
bind = $mainMod CTRL, BACKSPACE, exec, killall waybar; waybar
bind = $mainMod, BACKSPACE, exec, hyprctl reload

# Move focus with mainMod + vim keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Switch windows with mainMod + CTRL + vim keys
bind = $mainMod CTRL, H, swapwindow, l
bind = $mainMod CTRL, L, swapwindow, r
bind = $mainMod CTRL, K, swapwindow, u
bind = $mainMod CTRL, J, swapwindow, d

# Switch monitor a window is on with ALT + CTRL + vim keys
bind = ALT CTRL, H, movewindow, mon:1
bind = ALT CTRL, L, movewindow, mon:0

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, focusworkspaceoncurrentmonitor, 1
bind = $mainMod, 2, focusworkspaceoncurrentmonitor, 2
bind = $mainMod, 3, focusworkspaceoncurrentmonitor, 3
bind = $mainMod, 4, focusworkspaceoncurrentmonitor, 4
bind = $mainMod, 5, focusworkspaceoncurrentmonitor, 5
bind = $mainMod, 6, focusworkspaceoncurrentmonitor, 6
bind = $mainMod, 7, focusworkspaceoncurrentmonitor, 7
bind = $mainMod, 8, focusworkspaceoncurrentmonitor, 8
bind = $mainMod, 9, focusworkspaceoncurrentmonitor, 9
bind = $mainMod, 0, focusworkspaceoncurrentmonitor, 10

# Move active window to a workspace with mainMod + CTRL + [0-9]
bind = $mainMod CTRL, 1, movetoworkspace, 1
bind = $mainMod CTRL, 2, movetoworkspace, 2
bind = $mainMod CTRL, 3, movetoworkspace, 3
bind = $mainMod CTRL, 4, movetoworkspace, 4
bind = $mainMod CTRL, 5, movetoworkspace, 5
bind = $mainMod CTRL, 6, movetoworkspace, 6
bind = $mainMod CTRL, 7, movetoworkspace, 7
bind = $mainMod CTRL, 8, movetoworkspace, 8
bind = $mainMod CTRL, 9, movetoworkspace, 9
bind = $mainMod CTRL, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll or ALT + vim keys
bind = $mainMod, mouse_up, workspace, r+1
bind = ALT, J, workspace, r+1
bind = ALT, K, workspace, r-1
bind = $mainMod, mouse_down, workspace, r-1

# Move window to workspaces with ALT + CTRL + vim keys
bind = ALT CTRL, K, movetoworkspace, r-1
bind = ALT CTRL,J, movetoworkspace, r+1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod, code:85, resizeactive, 2% 0
bind = $mainMod SHIFT, code:85, resizeactive, 5% 0
bind = $mainMod, code:88, resizeactive, 0 2%
bind = $mainMod SHIFT, code:88, resizeactive, 0 5%
bind = $mainMod, code:83, resizeactive, -2% 0
bind = $mainMod SHIFT, code:83, resizeactive, -5% 0
bind = $mainMod, code:80, resizeactive, 0 -2%
bind = $mainMod SHIFT, code:80, resizeactive, 0 -5%

