windowrule = float,^(pavucontrol)$
windowrule = move 60% 25,^(pavucontrol)$
windowrule = size 40% 30%,^(pavucontrol)$
windowrule = float,^(blueman-manager)$
windowrule = move 60% 25,^(blueman-manager)$
windowrule = size 40% 30%,^(blueman-manager)$
windowrule = float,^(nm-connection-editor)$
windowrule = move 60% 25,^(nm-connection-editor)$
windowrule = size 40% 30%,^(nm-connection-editor)$
windowrule = float,^(galculator)$
windowrule = workspace special:btop, title:^(btop)$
windowrulev2 = opacity 0.8 0.8,class:^(kitty)$
windowrulev2 = animation popin,class:^(kitty)$,title:^(update-sys)$
windowrulev2 = opacity 0.8 0.8,class:^(Thunar)$
windowrulev2 = opacity 0.8 0.8,class:^(thunar)$
