#!/usr/bin/env bash

case "$1" in
update)
  kitty --title update-sys sh -c 'yay -Syu; flatpak update'
  echo "0" >"$HOME"/.local/state/updates
  ;;
check)
  AUR=$(yay -Qua | wc -l)
  OFFICIAL=$(checkupdates | wc -l)
  FLATPAK=$(flatpak remote-ls --updates | wc -l)
  echo $((OFFICIAL + AUR + FLATPAK)) >"$HOME"/.local/state/updates
  ;;
*)
  COUNT=$(<"$HOME"/.local/state/updates)
  if [[ "$COUNT" = "0" ]]; then
    echo ""
  else
    printf '{\"text\": \"\", \"tooltip\": \"%s\"}\n' "$COUNT" | jq --unbuffered --compact-output
  fi
  exit 0
  ;;
esac
