format = """
[](fg:#2f334d)\
$directory\
[](bg:#545c7e fg:#2f334d)\
$git_branch\
$git_status\
[](bg:#82aaff fg:#545c7e)\
[ ](fg:#82aaff)\
"""
command_timeout = 5000
add_newline = true

[directory]
style = "bg:#2f334d"
format = "[$path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = "󰕧"
".config" = ""

[git_branch]
symbol = ""
style = "bg:#545c7e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#545c7e"
format = '[$all_status$ahead_behind ]($style)'
