return {
  "gbprod/yanky.nvim",
  lazy = true,
  opts = {
    highlight = { timer = 150 },
  },
  keys = {
    { "<leader>fp", "<cmd>YankyRingHistory<cr>", desc = "Clipboard" },
    { "y", "<Plug>(YankyYank)", mode = { "n", "x" }, desc = "Yank Text" },
    { "]p", "<Plug>(YankyPutIndentAfterLinewise)", desc = "Put Indented After Cursor (Linewise)" },
    { "[p", "<Plug>(YankyPutIndentBeforeLinewise)", desc = "Put Indented Before Cursor (Linewise)" },
    { "]P", "<Plug>(YankyPutIndentAfterLinewise)", desc = "Put Indented After Cursor (Linewise)" },
    { "[P", "<Plug>(YankyPutIndentBeforeLinewise)", desc = "Put Indented Before Cursor (Linewise)" },
    { ">p", "<Plug>(YankyPutIndentAfterShiftRight)", desc = "Put Indented In After Cursor" },
    { "<p", "<Plug>(YankyPutIndentAfterShiftLeft)", desc = "Put Indented Out After Cursor" },
    { ">P", "<Plug>(YankyPutIndentBeforeShiftRight)", desc = "Put Indented In Before Cursor" },
    { "<P", "<Plug>(YankyPutIndentBeforeShiftLeft)", desc = "Put Indented Out Before Cursor" },
    { "gp", "<Plug>(YankyGPutAfterCharwiseJoined)", mode = { "n", "x" }, desc = "Put Text After Selection (Trimed)" },
    { "gP", "<Plug>(YankyGPutBeforeCharwiseJoined)", mode = { "n", "x" }, desc = "Put Text Before Selection (Trimed)" },
    { "p", "<Plug>(YankyGPutAfter)", mode = { "n", "x" }, desc = "Put After Selection" },
    { "P", "<Plug>(YankyGPutBefore)", mode = { "n", "x" }, desc = "Put Before Selection" },
    { "<C-P>", "<Plug>(YankyPreviousEntry)", desc = "Cycle Forward Through Yank History" },
    { "<C-N>", "<Plug>(YankyNextEntry)", desc = "Cycle Backward Through Yank History" },
  },
}
